FROM nginx:latest

COPY ./docker/nginx/conf.d  /etc/nginx/conf.d
COPY ./docker/nginx/html    /usr/share/nginx/html
COPY ./docker/nginx/images  /usr/share/nginx/images

CMD ["nginx", "-g", "daemon off;"]