spring:
  config:
    activate:
      on-profile: prod

  devtools:
    add-properties: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH_CLIENT_ID}
            clientSecret: ${OAUTH_CLIENT_SECRET}
            redirect-uri: ${FE_HTTP_URL}/login/oauth2/code/google
            scope:
              - email

app:
  fe:
    http-url: ${FE_HTTP_URL}
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    mbeanregistry:
      enabled: true
